defaults: &defaults
  access_key_id: ""
  secret_access_key: ""
development:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "dbc-ambrosia"
test:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "dbc-ambrosia"
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "dbc-ambrosia"
